<a href="https://colab.research.google.com/github/IvaYar/EkzoWood/blob/main/03_09_2024_01_transfer_learning_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
print(tf.__version__)

2.17.0


In [ ]:
scalar = tf.constant(6)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=6>

In [ ]:
scalar.ndim

0

In [ ]:
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
vector.ndim

1

In [ ]:
matrix = tf.constant([[10, 5],
                      [1, 9]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  5],
       [ 1,  9]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
another_matrix = tf.constant([[10., 7.],
                              [3., 2.],
                              [8., 9.]], dtype=tf.float16)

another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [ ]:
another_matrix.ndim

2

In [ ]:
tensor = tf.constant([[[1, 2, 3],
                       [4, 5, 6]],
                      [[7, 8, 9],
                       [10, 11, 12]],
                      [[13, 14, 15],
                       [16, 17, 18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [ ]:
tensor.ndim

3

In [ ]:
changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10, 7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
#You can't do that
#changeable_tensor[0] = 7
#changeable_tensor

In [ ]:
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [ ]:
# You can't do that
#unchangeable_tensor[0].assign(7)
#unchangleable_tensor

In [ ]:
random_3 = tf.random.Generator.from_seed(42)
random_3 = random_3.normal(shape=(3, 2))
random_4 = tf.random.Generator.from_seed(42)
random_4 = random_4.normal(shape=(3, 2))

random_4, random_3, random_4 == random_4

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

In [ ]:
random_3 = tf.random.Generator.from_seed(42)
random_3 = random_3.normal(shape=(3, 2))
random_4 = tf.random.Generator.from_seed(11)
random_4 = random_4.normal(shape=(3, 2))

random_3, random_4, random_1 == random_3, random_3 == random_4

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 0.27305737, -0.29925638],
        [-0.3652325 ,  0.61883307],
        [-1.0130816 ,  0.28291714]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[False, False],
        [False, False],
        [False, False]])>)

In [ ]:
not_shuffled = tf.constant([[10, 7],
                            [3, 4],
                            [2, 5]])

tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [ 3,  4],
       [10,  7]], dtype=int32)>

In [ ]:
tf.random.shuffle(not_shuffled, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [ 3,  4],
       [10,  7]], dtype=int32)>

In [ ]:
tf.random.set_seed(42)

tf.random.shuffle(not_shuffled, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [ ]:
tf.random.set_seed(42)

tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [ 2,  5],
       [10,  7]], dtype=int32)>

In [ ]:
tf.ones(shape=(3, 2))

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)>

In [ ]:
tf.zeros(shape=(3, 2))

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.],
       [0., 0.]], dtype=float32)>

In [ ]:
import numpy as np
numpy_A = np.arange(1, 25, dtype=np.int32) # create a NumPy array between 1 and 25
A = tf.constant(numpy_A,
                shape=[2, 4, 3]) # note: the shape total (2*4*3) has to match the number of elements in the array
numpy_A, A

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32),
 <tf.Tensor: shape=(2, 4, 3), dtype=int32, numpy=
 array([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9],
         [10, 11, 12]],
 
        [[13, 14, 15],
         [16, 17, 18],
         [19, 20, 21],
         [22, 23, 24]]], dtype=int32)>)

In [ ]:
rank_4_tensor = tf.zeros([2, 3, 4, 5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

HomeWork

Create a vector, scalar, matrix and tensor with values of your choosing using tf.constant().

In [ ]:
v = tf.constant([1,2])
s = tf.constant(1)
m = tf.constant([[1,2],
                        [1,2]])
t = tf.constant([[[1,2,3],
                         [4,5,6],
                         [7,8,9]],
                        [[1,2,3],
                         [4,5,6],
                         [7,8,9]],
                        [[1,2,3],
                         [4,5,6],
                         [7,8,9]]])

In [ ]:
v,s,m,t

(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>,
 <tf.Tensor: shape=(), dtype=int32, numpy=1>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[1, 2],
        [1, 2]], dtype=int32)>,
 <tf.Tensor: shape=(3, 3, 3), dtype=int32, numpy=
 array([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],
 
        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],
 
        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]], dtype=int32)>)

Find the shape, rank and size of the tensors you created in 1.

In [ ]:
def shapeRankSize(name,i):
  print("For {}:".format(name))
  print("    Shape is {}".format(i.shape))
  print("    Rank is {}".format(tf.rank(i)))
  print("    Size is {}\n".format(tf.size(i).numpy()))

In [ ]:
shapeRankSize("vector",v)
shapeRankSize("scalar",s)
shapeRankSize("matrix",m)
shapeRankSize("tensor",t)

For vector:
    Shape is (2,)
    Rank is 1
    Size is 2

For scalar:
    Shape is ()
    Rank is 0
    Size is 1

For matrix:
    Shape is (2, 2)
    Rank is 2
    Size is 4

For tensor:
    Shape is (3, 3, 3)
    Rank is 3
    Size is 27



Create two tensors containing random values between 0 and 1 with shape [5, 300].

In [ ]:
random_1 = tf.random.uniform(minval=0,maxval=1,shape=(5,300))
random_2 = tf.random.uniform(minval=0,maxval=1,shape=(5,300))

In [ ]:
random_1,random_2

(<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[0.140059  , 0.7625865 , 0.9331671 , ..., 0.5123167 , 0.6881361 ,
         0.3382938 ],
        [0.29091585, 0.8111967 , 0.8336052 , ..., 0.0310868 , 0.25958502,
         0.31451488],
        [0.45210385, 0.10351062, 0.9698291 , ..., 0.8383945 , 0.784729  ,
         0.06423211],
        [0.4395399 , 0.06976593, 0.6771873 , ..., 0.5769315 , 0.29718387,
         0.5162878 ],
        [0.92730105, 0.9681965 , 0.26524258, ..., 0.0795511 , 0.688795  ,
         0.37864125]], dtype=float32)>,
 <tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[0.8936908 , 0.88520634, 0.9722564 , ..., 0.27908385, 0.89075327,
         0.01845598],
        [0.62826145, 0.133564  , 0.6773287 , ..., 0.72809696, 0.49329948,
         0.18942618],
        [0.08103812, 0.03707457, 0.8994708 , ..., 0.18256724, 0.09080136,
         0.00902736],
        [0.85063124, 0.7135165 , 0.5785947 , ..., 0.35243332, 0.5895219 ,
         0.6850085 ],
        [0.07663

Multiply the two tensors you created in 3 using matrix multiplication.

In [ ]:
tf.matmul(random_1,tf.transpose(random_2))

Multiply the two tensors you created in 3 using dot product.

In [ ]:
tf.tensordot(random_1,tf.transpose(random_2),axes=1)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[70.614975, 78.2559  , 67.491196, 76.04034 , 67.69641 ],
       [69.131905, 76.407715, 70.97185 , 75.886185, 69.64664 ],
       [68.21159 , 73.8857  , 71.029274, 73.348114, 67.59726 ],
       [71.29883 , 81.60474 , 74.61708 , 78.839066, 72.34537 ],
       [67.28436 , 74.408615, 65.73064 , 71.4599  , 69.26482 ]],
      dtype=float32)>

Create a tensor with random values between 0 and 1 with shape [224, 224, 3].

In [ ]:
random_3 = tf.random.uniform([224, 224, 3],0,1)
random_3

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[0.18192208, 0.09493959, 0.6317812 ],
        [0.8141421 , 0.28745008, 0.7737336 ],
        [0.04462767, 0.71553636, 0.80468047],
        ...,
        [0.68386567, 0.27786005, 0.74453914],
        [0.8226893 , 0.71559596, 0.14721501],
        [0.8584467 , 0.03009713, 0.0536474 ]],

       [[0.61138856, 0.38803148, 0.08269775],
        [0.8882102 , 0.40674305, 0.5170288 ],
        [0.60512745, 0.55607986, 0.40903664],
        ...,
        [0.8795278 , 0.6838596 , 0.13690436],
        [0.8656707 , 0.5734513 , 0.24968112],
        [0.5121559 , 0.8395573 , 0.91569114]],

       [[0.32561028, 0.7831812 , 0.37629557],
        [0.7459601 , 0.15828037, 0.7154614 ],
        [0.9088414 , 0.3433262 , 0.67376494],
        ...,
        [0.5460036 , 0.70619977, 0.42546737],
        [0.9387984 , 0.6081183 , 0.90944743],
        [0.04331839, 0.3652314 , 0.27456224]],

       ...,

       [[0.22791576, 0.6625606 , 0.05335128],
        [0.27

Find the min and max values of the tensor you created in 6.

In [ ]:
print("{} - min value {} - max value".format(tf.reduce_min(random_3).numpy(),tf.reduce_max(random_3).numpy()))

8.344650268554688e-07 - min value 0.9999996423721313 - max value


Created a tensor with random values of shape [1, 224, 224, 3] then squeeze it to change the shape to [224, 224, 3].

In [ ]:
random_4 = tf.random.uniform([1,224,224,3])
random_4.shape

TensorShape([1, 224, 224, 3])

In [ ]:
random_4_squeezed = tf.squeeze(random_4)
random_4_squeezed.shape

TensorShape([224, 224, 3])

Create a tensor with shape [10] using your own choice of values, then find the index which has the maximum value.

In [ ]:
random_5 = tf.random.uniform([10],0,10)
random_5

<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([9.648534 , 1.7411888, 2.8085542, 1.4319694, 2.9220033, 2.2992861,
       8.547932 , 0.6670332, 9.244417 , 0.8933878], dtype=float32)>

In [ ]:
print("index {} has the maximum value".format(tf.argmax(random_5).numpy()))

index 0 has the maximum value


One-hot encode the tensor you created in 9.

In [ ]:
tf.cast(random_5.numpy().tolist(),tf.int32)

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([9, 1, 2, 1, 2, 2, 8, 0, 9, 0], dtype=int32)>

In [ ]:
tf.one_hot(tf.cast(random_5.numpy().tolist(),tf.int32),depth=tf.size(random_5).numpy(),on_value="|",off_value="-")

<tf.Tensor: shape=(10, 10), dtype=string, numpy=
array([[b'-', b'-', b'-', b'-', b'-', b'-', b'-', b'-', b'-', b'|'],
       [b'-', b'|', b'-', b'-', b'-', b'-', b'-', b'-', b'-', b'-'],
       [b'-', b'-', b'|', b'-', b'-', b'-', b'-', b'-', b'-', b'-'],
       [b'-', b'|', b'-', b'-', b'-', b'-', b'-', b'-', b'-', b'-'],
       [b'-', b'-', b'|', b'-', b'-', b'-', b'-', b'-', b'-', b'-'],
       [b'-', b'-', b'|', b'-', b'-', b'-', b'-', b'-', b'-', b'-'],
       [b'-', b'-', b'-', b'-', b'-', b'-', b'-', b'-', b'|', b'-'],
       [b'|', b'-', b'-', b'-', b'-', b'-', b'-', b'-', b'-', b'-'],
       [b'-', b'-', b'-', b'-', b'-', b'-', b'-', b'-', b'-', b'|'],
       [b'|', b'-', b'-', b'-', b'-', b'-', b'-', b'-', b'-', b'-']],
      dtype=object)>